//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SplitePacker.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SplitePacker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   パック失敗
        ///バックグラウンド実行に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_BG_ARGS_EMPTY {
            get {
                return ResourceManager.GetString("IDS_BG_ARGS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バックグラウンドスレッド終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_BG_END {
            get {
                return ResourceManager.GetString("IDS_BG_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パック中です... {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_BG_PACK_FILE {
            get {
                return ResourceManager.GetString("IDS_BG_PACK_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パック失敗
        ///無効なパスが指定されました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_BG_PACK_INVALID_PATH {
            get {
                return ResourceManager.GetString("IDS_BG_PACK_INVALID_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パック失敗
        ///画像が入りきりませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_BG_PACK_OVERFLOW {
            get {
                return ResourceManager.GetString("IDS_BG_PACK_OVERFLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パック画像を保存しています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_BG_PACK_SAVE {
            get {
                return ResourceManager.GetString("IDS_BG_PACK_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バックグラウンドスレッド開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_BG_START {
            get {
                return ResourceManager.GetString("IDS_BG_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期化ボタンクリック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_CLEAR_CLICK {
            get {
                return ResourceManager.GetString("IDS_MAIN_CLEAR_CLICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期化処理で例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_CLEAR_EXCEPTION {
            get {
                return ResourceManager.GetString("IDS_MAIN_CLEAR_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FormClosingで例外が発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_CLOSING_EXCEPTION {
            get {
                return ResourceManager.GetString("IDS_MAIN_CLOSING_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更が保存されていませんが
        ///終了してもよろしいでしょうか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_CLOSING_NO_SAVE {
            get {
                return ResourceManager.GetString("IDS_MAIN_CLOSING_NO_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RunWorkerCompleted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_COMPLETED {
            get {
                return ResourceManager.GetString("IDS_MAIN_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成ボタンクリック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_CREATE_CLICK {
            get {
                return ResourceManager.GetString("IDS_MAIN_CREATE_CLICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パック画像横幅/縦幅が２の累乗ではありませんが
        ///作成してよいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_CREATE_NO_TWO_EXP_A {
            get {
                return ResourceManager.GetString("IDS_MAIN_CREATE_NO_TWO_EXP_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パック画像縦幅が２の累乗ではありませんが
        ///作成してよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_CREATE_NO_TWO_EXP_H {
            get {
                return ResourceManager.GetString("IDS_MAIN_CREATE_NO_TWO_EXP_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パック画像横幅が２の累乗ではありませんが
        ///作成してよいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_CREATE_NO_TWO_EXP_W {
            get {
                return ResourceManager.GetString("IDS_MAIN_CREATE_NO_TWO_EXP_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DragDrop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_DRAG_DROP {
            get {
                return ResourceManager.GetString("IDS_MAIN_DRAG_DROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drop処理で例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_DRAG_DROP_EXCEPTION {
            get {
                return ResourceManager.GetString("IDS_MAIN_DRAG_DROP_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DragEnetr に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_DRAG_ENETR {
            get {
                return ResourceManager.GetString("IDS_MAIN_DRAG_ENETR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DragEnterで例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_DRAG_ENTER_EXCEPTION {
            get {
                return ResourceManager.GetString("IDS_MAIN_DRAG_ENTER_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リストにファイルを追加 [{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_DROP_ADD {
            get {
                return ResourceManager.GetString("IDS_MAIN_DROP_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォーマット異常です。エクスプローラーからのファイルDropのみ有効です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_DROP_FORMAT_FAILED {
            get {
                return ResourceManager.GetString("IDS_MAIN_DROP_FORMAT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パック失敗
        ///パック終了処理中に例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_END_EXCEPTION {
            get {
                return ResourceManager.GetString("IDS_MAIN_END_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パック失敗
        ///画像パック中に例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_END_PROC_EXCEPTION {
            get {
                return ResourceManager.GetString("IDS_MAIN_END_PROC_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パック成功 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_END_SUCCESS {
            get {
                return ResourceManager.GetString("IDS_MAIN_END_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル選択で例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_FILE_EXCEPTION {
            get {
                return ResourceManager.GetString("IDS_MAIN_FILE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   縦幅変更イベントで例外発生 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_HEIGHT_CHANGE_EXCEPTION {
            get {
                return ResourceManager.GetString("IDS_MAIN_HEIGHT_CHANGE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読込時に例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_LOAD_EXCEPTION {
            get {
                return ResourceManager.GetString("IDS_MAIN_LOAD_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの読込に失敗しました。(path={0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_LOAD_FAILED {
            get {
                return ResourceManager.GetString("IDS_MAIN_LOAD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更が保存されていませんが
        ///読込してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_LOAD_NOT_SAVED {
            get {
                return ResourceManager.GetString("IDS_MAIN_LOAD_NOT_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読込パスが指定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_LOAD_PATH_EMPTY {
            get {
                return ResourceManager.GetString("IDS_MAIN_LOAD_PATH_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メッセージ表示時に例外発生 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_MSG_EXCEPTION {
            get {
                return ResourceManager.GetString("IDS_MAIN_MSG_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パック実行中のため終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_PACKKING {
            get {
                return ResourceManager.GetString("IDS_MAIN_PACKKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パス変更イベントで例外発生 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_PATH_CHANGE_EXCEPTION {
            get {
                return ResourceManager.GetString("IDS_MAIN_PATH_CHANGE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   例外が発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_PROGRESS_EXCEPTION {
            get {
                return ResourceManager.GetString("IDS_MAIN_PROGRESS_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存時に例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_SAVE_EXCEPTION {
            get {
                return ResourceManager.GetString("IDS_MAIN_SAVE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存パスが指定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_SAVE_PATH_EMPTY {
            get {
                return ResourceManager.GetString("IDS_MAIN_SAVE_PATH_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル選択ボタンクリック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_SELECT_FILE_CLICK {
            get {
                return ResourceManager.GetString("IDS_MAIN_SELECT_FILE_CLICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読込クリック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_SELECT_LOAD_CLICK {
            get {
                return ResourceManager.GetString("IDS_MAIN_SELECT_LOAD_CLICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存クリック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_SELECT_SAVE_CLICK {
            get {
                return ResourceManager.GetString("IDS_MAIN_SELECT_SAVE_CLICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shownで例外発生 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_SHOWN_EXCEPTION {
            get {
                return ResourceManager.GetString("IDS_MAIN_SHOWN_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パック失敗
        ///処理に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_START_EXCEPTION {
            get {
                return ResourceManager.GetString("IDS_MAIN_START_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パック失敗
        ///画像が空です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_START_IMAGE_EMPTY {
            get {
                return ResourceManager.GetString("IDS_MAIN_START_IMAGE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パック失敗
        ///ファイル名が空です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_START_PATH_EMPTY {
            get {
                return ResourceManager.GetString("IDS_MAIN_START_PATH_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}{2} - {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_TITLE_FORMAT {
            get {
                return ResourceManager.GetString("IDS_MAIN_TITLE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_TITLE_UPDATE_MARK {
            get {
                return ResourceManager.GetString("IDS_MAIN_TITLE_UPDATE_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   横幅変更イベントで例外発生 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MAIN_WIDTH_CHANGE_EXCEPTION {
            get {
                return ResourceManager.GetString("IDS_MAIN_WIDTH_CHANGE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VisualButtonクリックで例外発生 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_VBTN_CLICK_EXCEPTION {
            get {
                return ResourceManager.GetString("IDS_VBTN_CLICK_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VisualButtonイネーブルチェンジで例外発生 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_VBTN_ENABLE_EXCEPTION {
            get {
                return ResourceManager.GetString("IDS_VBTN_ENABLE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VisualButtonロードで例外発生 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_VBTN_LOAD_EXCEPTION {
            get {
                return ResourceManager.GetString("IDS_VBTN_LOAD_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VisualButton画像読込で例外発生 (path={0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_VBTN_LOAD_IMG_EXCEPTION {
            get {
                return ResourceManager.GetString("IDS_VBTN_LOAD_IMG_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VisualButton画像読込 (pathがnull) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_VBTN_LOAD_IMG_IS_NULL {
            get {
                return ResourceManager.GetString("IDS_VBTN_LOAD_IMG_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VisualButton画像読込 (path={0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_VBTN_LOAD_IMG_OPEN {
            get {
                return ResourceManager.GetString("IDS_VBTN_LOAD_IMG_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VisualButton画像読込成功 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_VBTN_LOAD_IMG_SUCCESS {
            get {
                return ResourceManager.GetString("IDS_VBTN_LOAD_IMG_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VisualButtonマウスダウンで例外発生 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_VBTN_MDOWN_EXCEPTION {
            get {
                return ResourceManager.GetString("IDS_VBTN_MDOWN_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VisualButtonマウスアップで例外発生 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_VBTN_MUP_EXCEPTION {
            get {
                return ResourceManager.GetString("IDS_VBTN_MUP_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon spritepacker {
            get {
                object obj = ResourceManager.GetObject("spritepacker", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
